import type { GiftPhoto } from "@/lib/gift/schema";

/** Generated by scripts/process-demo-photos — sample photos used by every template demo. */
export const DEMO_PHOTOS = {
  p1: { id: "p1", url: "/demo/photos/p1.webp", width: 896, height: 1200, alt: "Two hands intertwined on a café table", caption: "Our first coffee. You stole my sugar." },
  p2: { id: "p2", url: "/demo/photos/p2.webp", width: 896, height: 1200, alt: "A couple walking down a Lisbon street at dusk", caption: "Lisbon, the night we got lost on purpose" },
  p3: { id: "p3", url: "/demo/photos/p3.webp", width: 1024, height: 1024, alt: "A birthday cake with lit candles", caption: "Thirty candles, one wish" },
  p4: { id: "p4", url: "/demo/photos/p4.webp", width: 1200, height: 896, alt: "A golden retriever puppy on a picnic blanket", caption: "The day Nube chose us" },
  p5: { id: "p5", url: "/demo/photos/p5.webp", width: 1200, height: 896, alt: "A glowing tent under the Milky Way", caption: "No signal. No plans. Just stars." },
  p6: { id: "p6", url: "/demo/photos/p6.webp", width: 896, height: 1200, alt: "Rain on a night train window", caption: "The 23:40 to you" },
  p7: { id: "p7", url: "/demo/photos/p7.webp", width: 1200, height: 896, alt: "Two bicycles by the sea", caption: "July, and everything was slow" },
  p8: { id: "p8", url: "/demo/photos/p8.webp", width: 1024, height: 1024, alt: "A handwritten note in an open book", caption: "You leave notes. I keep every one." },
} as const satisfies Record<string, GiftPhoto>;

export type DemoPhotoId = keyof typeof DEMO_PHOTOS;

export function demoPhotos(ids: DemoPhotoId[], captions?: Partial<Record<DemoPhotoId, string>>): GiftPhoto[] {
  return ids.map((id) => ({ ...DEMO_PHOTOS[id], caption: captions?.[id] ?? DEMO_PHOTOS[id].caption }));
}
